<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    1、基本用法
    async函数返回一个Promise对象，可以使用then方法添加回调函数。当函数执行的时候，一旦遇上await就会先返回，等异步操作完成，再执行函数体内后面的语句。
    <script>
      async function getStockPriceByName(name) {
        const symbol = await getStockSymbol(name);
        const stockPrice = await getStockPrice(symbol);
        return stockPrice;
      }
      getStockPriceByName("goog").then(function (result) {
        console.log(result);
      });
    </script>
    ------------------------------------------------------------------------------------------
    2、返回Promise对象
    async函数内部语句返回的值，会成为then方法回调函数的参数。async函数内部抛出错误，会导致返回的
    Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。
    <script>
      async function f() {
        return "hello world";
      }
      f().then((v) => console.log(v));
      //"hello world"
    </script>
    ------------------------------------------------------------------------------------------
    3、Promise对象状态的变化
    只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数。async函数返回的
    Promise 对象，必须等到内部所有await命令后面的 Promise
    对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误。
    <script>
      async function getTitle(url) {
        let response = await fetch(url);
        let html = await response.text();
        return html.match(/<title>([\s\S]+)<\/title>/i)[1];
      }
      getTitle("https://tc39.github.io/ecma262/").then(console.log);
      // "ECMAScript 2017 Language Specification"
    </script>
    函数getTitle内部有三个操作：抓取网页、取出文本、匹配页面标题。只有这三个操作全部完成，才会执行then方法里面的console.log。
    ------------------------------------------------------------------------------------------
    4、await命令
    await命令后面是一个Promise对象或thenable对象，返回对象的结果。任何一个await语句后面的
    Promise 对象变为reject状态，那么整个async函数都会中断执行。
    <script>
      async function f() {
        await Promise.reject("出错了");
        await Promise.resolve("hello world"); // 不会执行
      }
    </script>
    任何一个await语句后面的Promise对象变为reject状态，那么整个async函数都会中断执行。如果希望前一个异步操作失败，也不要中断后面的异步操作。这时可以将第一个await放在try...catch结构里面，这样不管这个异步操作是否成功，第二个await都会执行。
    <script>
      async function f() {
        try {
          await Promise.reject("出错了");
        } catch (e) {}
        return await Promise.resolve("hello world");
      }
      f().then((v) => console.log(v));
      // hello world
    </script>
  </body>
</html>
